buildscript {
    repositories {
        jcenter()
        maven { url = "https://maven.minecraftforge.net" }
        maven { url = "https://maven.minecraftforge.net/maven" }
        maven { url = "https://repo.spongepowered.org/maven" }
        maven { url = "https://jitpack.io" }
    }
    dependencies {
        classpath 'com.github.Debuggingss:ForgeGradle:c5a0ae9'
    }
}

apply plugin: 'net.minecraftforge.gradle.forge'

version = "1.0.0"
group = "com.rapit.client"
archivesBaseName = "RapitClient"

sourceCompatibility = JavaVersion.VERSION_1_8
targetCompatibility = JavaVersion.VERSION_1_8

minecraft {
    version = "1.8.9-11.15.1.2318"
    runDir = "run"
    mappings = "stable_22"
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", project.minecraft.version

    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version': project.version, 'mcversion': project.minecraft.version
    }

    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

jar {
    manifest {
        attributes(
            'FMLCorePlugin': 'com.rapit.client.core.RapitCoreMod',
            'FMLCorePluginContainsFMLMod': 'true',
            'ForceLoadAsMod': 'true'
        )
    }
}
